image: maven:3.6-jdk-11

stages:
  - test
  - deploy

# configure proxy to access to maven central
before_script:
  
  # - echo $HTTPS_PROXY
  # - echo $HTTP_PROXY

  - export HTTP_PROXY_PROTOCOL="$(echo $HTTP_PROXY | awk -F':' '{print $1}')"
  - export HTTP_PROXY_PROTOCOL="${HTTP_PROXY_PROTOCOL:-http}"
  - export HTTP_PROXY_HOST="$(echo $HTTP_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $1}')"
  - export HTTP_PROXY_PORT="$(echo $HTTP_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $2}')"
  - export HTTP_PROXY_PORT="${HTTP_PROXY_PORT:-80}"
  # for the port, env variable seems not work, so we modify the ci settings file
  - sed -i 's/${env.HTTP_PROXY_PORT}/'"$HTTP_PROXY_PORT"'/g' ci_settings.xml

  - export HTTPS_PROXY_PROTOCOL="$(echo $HTTPS_PROXY | awk -F':' '{print $1}')"
  - export HTTPS_PROXY_PROTOCOL="${HTTPS_PROXY_PROTOCOL:-https}"
  - export HTTPS_PROXY_HOST="$(echo $HTTPS_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $1}')"
  - export HTTPS_PROXY_PORT="$(echo $HTTPS_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $2}')"
  - export HTTPS_PROXY_PORT="${HTTPS_PROXY_PORT:-443}"
  # for the port, env variable seems not work, so we modify the ci settings file
  - sed -i 's/${env.HTTPS_PROXY_PORT}/'"$HTTPS_PROXY_PORT"'/g' ci_settings.xml

  # - echo $HTTP_PROXY_PROTOCOL
  # - echo $HTTP_PROXY_HOST
  # - echo $HTTP_PROXY_PORT
  # - echo $HTTPS_PROXY_PROTOCOL
  # - echo $HTTPS_PROXY_HOST
  # - echo $HTTPS_PROXY_PORT

jerboa_modeler_viewer_dev_tests:
  stage: test
  script:
    - mvn -s ci_settings.xml -f pom.xml clean test -P test
  allow_failure: true
  except:
    - tags

jerboa_modeler_viewer_tag_tests:
  stage: test
  script:
    - mvn -s ci_settings.xml -f pom.xml clean test -P test
  allow_failure: true # should be false !
  only:
    - tags

jerboa_modeler_viewer_dev:
  stage: deploy
  script:
    - mvn -s ci_settings.xml -f pom.xml deploy -DskipTests -Dchangelist= -Dsha1=-$CI_COMMIT_SHORT_SHA
  except:
    - tags
    - master
    - main

jerboa_modeler_viewer_main:
  stage: deploy
  script:
    - mvn -s ci_settings.xml -f pom.xml deploy -DskipTests -Dsha1=-$CI_COMMIT_SHORT_SHA
  only:
    - master
    - main

jerboa_modeler_viewer_release:
  stage: deploy
  script:
    - mvn -s ci_settings.xml -f pom.xml deploy -DskipTests -Dchangelist= -Drevision=$CI_COMMIT_TAG
  only:
    - tags