image: maven:3.6-jdk-11

stages:
  - test_connectivity
#  - test
  - deploy


check_connectivity:
  stage: test_connectivity
  script:
    - echo "Vérification de la connexion à Maven Central..."
    - curl -v https://repo.maven.apache.org/maven2/

jerboa_editor_dev_tests:
  stage: test
  script:
    - mvn -U -f pom.xml clean test -P test
  allow_failure: true
  except:
    - tags

jerboa_editor_tag_tests:
  stage: test
  script:
    - mvn -U -f pom.xml clean test -P test
  allow_failure: true # should be false !
  only:
    - tags

jerboa_editor_dev:
  stage: deploy
  script:
    - mvn -e -U -f pom.xml deploy -P release -DskipTests -Dchangelist= -Dsha1=-$CI_COMMIT_SHORT_SHA
#    - mvn -e -U -f pom.xml deploy -P commandline -DskipTests -Dchangelist= -Dsha1=-$CI_COMMIT_SHORT_SHA -DnameSuffix="-command-line"
  except:
    - tags
    - master
    - main

jerboa_editor_main:
  stage: deploy
  script:
    - mvn -U -f pom.xml deploy -P release -DskipTests -Dsha1=-$CI_COMMIT_SHORT_SHA
#    - mvn -U -f pom.xml deploy -P commandline -DskipTests -Dsha1=-$CI_COMMIT_SHORT_SHA -DnameSuffix="-command-line"
  only:
    - master
    - main

jerboa_editor_release:
  stage: deploy
  script:
    - mvn -U -f pom.xml deploy -P release -DskipTests -Dchangelist= -Drevision=$CI_COMMIT_TAG
#    - mvn -U -f pom.xml deploy -P commandline -DskipTests -Dchangelist= -Drevision=$CI_COMMIT_TAG -DnameSuffix="-command-line"
  only:
    - tags