image: maven:3.6-jdk-11

stages:
  - test
  - deploy


before_script:
  - export HTTP_PROXY_PROTOCOL="$(echo $HTTP_PROXY | awk -F':' '{print $1}')"
  - export HTTP_PROXY_PROTOCOL="${HTTP_PROXY_PROTOCOL:-http}"
  - export HTTP_PROXY_HOST="$(echo $HTTP_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $1}')"
  - export HTTP_PROXY_PORT="$(echo $HTTP_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $2}')"
  - export HTTP_PROXY_PORT="${HTTP_PROXY_PORT:-80}"
  - export HTTPS_PROXY_PROTOCOL="$(echo $HTTPS_PROXY | awk -F':' '{print $1}')"
  - export HTTPS_PROXY_PROTOCOL="${HTTPS_PROXY_PROTOCOL:-https}"
  - export HTTPS_PROXY_HOST="$(echo $HTTPS_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $1}')"
  - export HTTPS_PROXY_PORT="$(echo $HTTPS_PROXY | awk -F/ '{print $3}' | awk -F':' '{print $2}')"
  - export HTTPS_PROXY_PORT="${HTTPS_PROXY_PORT:-443}"
  - export MAVEN_OPTS="-Dhttp.proxyHost=$HTTP_PROXY_HOST -Dhttp.proxyPort=$HTTP_PROXY_PORT -Dhttps.proxyHost=$HTTPS_PROXY_HOST -Dhttps.proxyPort=$HTTPS_PROXY_PORT"


jerboa_editor_dev_tests:
  stage: test
  script:
    - mvn -U -f pom.xml clean test -P test
  allow_failure: true
  except:
    - tags

jerboa_editor_tag_tests:
  stage: test
  script:
    - mvn -U -f pom.xml clean test -P test 
  allow_failure: true # should be false !
  only:
    - tags

jerboa_editor_dev:
  stage: deploy
  script:
    - mvn -e -U -f pom.xml package -P release -DskipTests -Dchangelist= -Dsha1=-$CI_COMMIT_SHORT_SHA
    - mvn -e -U -f pom.xml package -P commandline -DskipTests -Dchangelist= -Dsha1=-$CI_COMMIT_SHORT_SHA -DnameSuffix="cli-"
  except:
    - tags
    - master
    - main

jerboa_editor_main:
  stage: deploy
  script:
    - mvn -s ci_settings.xml -U -f pom.xml deploy -P release -DskipTests -Dsha1=-$CI_COMMIT_SHORT_SHA -DnameSuffix=""
    - mvn -s ci_settings.xml -U -f pom.xml deploy -P commandline -DskipTests -Dsha1=-$CI_COMMIT_SHORT_SHA -DnameSuffix="cli-"
  only:
    - master
    - main

jerboa_editor_release:
  stage: deploy
  script:
    - mvn -s ci_settings.xml -U -f pom.xml deploy -P release -DskipTests -Dchangelist= -Drevision=$CI_COMMIT_TAG
    - mvn -s ci_settings.xml -U -f pom.xml deploy -P commandline -DskipTests -Dchangelist= -Drevision=$CI_COMMIT_TAG -DnameSuffix="cli-"
  only:
    - tags